// Generated by CIRCT firtool-1.42.0
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
    `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
  `endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
  `endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
  `endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
      `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
      `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
    `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module Tile(	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
  input         clock,	// <stdin>:4:11, :39:11, :74:11, :109:11, :144:11, :179:11, :214:11, :249:11, :284:11, :319:11, :354:11, :389:11, :424:11, :459:11, :494:11, :529:11, :564:11, :599:11, :634:11, :669:11, :704:11, :739:11, :774:11, :809:11, :844:11, :879:11, :914:11, :949:11, :984:11, :1019:11, :1054:11, :1089:11, :1124:11, :1159:11, :1194:11, :1229:11, :1264:11, :1299:11, :1334:11, :1369:11, :1404:11, :1439:11, :1474:11, :1509:11, :1544:11, :1579:11, :1614:11, :1649:11
                reset,	// <stdin>:5:11, :40:11, :75:11, :110:11, :145:11, :180:11, :215:11, :250:11, :285:11, :320:11, :355:11, :390:11, :425:11, :460:11, :495:11, :530:11, :565:11, :600:11, :635:11, :670:11, :705:11, :740:11, :775:11, :810:11, :845:11, :880:11, :915:11, :950:11, :985:11, :1020:11, :1055:11, :1090:11, :1125:11, :1160:11, :1195:11, :1230:11, :1265:11, :1300:11, :1335:11, :1370:11, :1405:11, :1440:11, :1475:11, :1510:11, :1545:11, :1580:11, :1615:11, :1650:11
  input  [7:0]  io_a_io_in_0,	// src/main/scala/gemm/gemm.scala:19:17
                io_a_io_in_1,	// src/main/scala/gemm/gemm.scala:19:17
                io_a_io_in_2,	// src/main/scala/gemm/gemm.scala:19:17
                io_a_io_in_3,	// src/main/scala/gemm/gemm.scala:19:17
                io_b_io_in_0,	// src/main/scala/gemm/gemm.scala:19:17
                io_b_io_in_1,	// src/main/scala/gemm/gemm.scala:19:17
                io_b_io_in_2,	// src/main/scala/gemm/gemm.scala:19:17
                io_b_io_in_3,	// src/main/scala/gemm/gemm.scala:19:17
  input         io_in_control_data_in_valid,	// src/main/scala/gemm/gemm.scala:19:17
  output [31:0] io_c_io_out,	// src/main/scala/gemm/gemm.scala:19:17
  output        io_data_out_valid	// src/main/scala/gemm/gemm.scala:19:17
);

  reg  [31:0] accumulation_reg;	// src/main/scala/gemm/gemm.scala:21:35
  reg         chek_data_in_valid;	// src/main/scala/gemm/gemm.scala:22:37
  wire [15:0] mul_add_result =
    {8'h0, io_a_io_in_0} * {8'h0, io_b_io_in_0} + {8'h0, io_a_io_in_1}
    * {8'h0, io_b_io_in_1} + {8'h0, io_a_io_in_2} * {8'h0, io_b_io_in_2}
    + {8'h0, io_a_io_in_3} * {8'h0, io_b_io_in_3};	// src/main/scala/gemm/gemm.scala:23:30, :31:52, :34:71
  always @(posedge clock) begin	// <stdin>:4:11, :39:11, :74:11, :109:11, :144:11, :179:11, :214:11, :249:11, :284:11, :319:11, :354:11, :389:11, :424:11, :459:11, :494:11, :529:11, :564:11, :599:11, :634:11, :669:11, :704:11, :739:11, :774:11, :809:11, :844:11, :879:11, :914:11, :949:11, :984:11, :1019:11, :1054:11, :1089:11, :1124:11, :1159:11, :1194:11, :1229:11, :1264:11, :1299:11, :1334:11, :1369:11, :1404:11, :1439:11, :1474:11, :1509:11, :1544:11, :1579:11, :1614:11, :1649:11
    if (reset) begin	// <stdin>:4:11, :39:11, :74:11, :109:11, :144:11, :179:11, :214:11, :249:11, :284:11, :319:11, :354:11, :389:11, :424:11, :459:11, :494:11, :529:11, :564:11, :599:11, :634:11, :669:11, :704:11, :739:11, :774:11, :809:11, :844:11, :879:11, :914:11, :949:11, :984:11, :1019:11, :1054:11, :1089:11, :1124:11, :1159:11, :1194:11, :1229:11, :1264:11, :1299:11, :1334:11, :1369:11, :1404:11, :1439:11, :1474:11, :1509:11, :1544:11, :1579:11, :1614:11, :1649:11
      accumulation_reg <= 32'h0;	// src/main/scala/gemm/gemm.scala:21:35
      chek_data_in_valid <= 1'h0;	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10, src/main/scala/gemm/gemm.scala:22:37
    end
    else begin	// <stdin>:4:11, :39:11, :74:11, :109:11, :144:11, :179:11, :214:11, :249:11, :284:11, :319:11, :354:11, :389:11, :424:11, :459:11, :494:11, :529:11, :564:11, :599:11, :634:11, :669:11, :704:11, :739:11, :774:11, :809:11, :844:11, :879:11, :914:11, :949:11, :984:11, :1019:11, :1054:11, :1089:11, :1124:11, :1159:11, :1194:11, :1229:11, :1264:11, :1299:11, :1334:11, :1369:11, :1404:11, :1439:11, :1474:11, :1509:11, :1544:11, :1579:11, :1614:11, :1649:11
      if (chek_data_in_valid)	// src/main/scala/gemm/gemm.scala:22:37
        accumulation_reg <= 32'h0;	// src/main/scala/gemm/gemm.scala:21:35
      else if (io_in_control_data_in_valid)	// src/main/scala/gemm/gemm.scala:19:17
        accumulation_reg <= {16'h0, mul_add_result};	// src/main/scala/gemm/gemm.scala:21:35, :23:30, :36:26
      chek_data_in_valid <= io_in_control_data_in_valid;	// src/main/scala/gemm/gemm.scala:22:37
    end
  end // always @(posedge)
  `ifndef SYNTHESIS	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
    `ifdef FIRRTL_BEFORE_INITIAL	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
      `FIRRTL_BEFORE_INITIAL	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
      automatic logic [31:0] _RANDOM[0:1];	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
      `ifdef INIT_RANDOM_PROLOG_	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
        `INIT_RANDOM_PROLOG_	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
        end	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
        accumulation_reg = _RANDOM[1'h0];	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10, src/main/scala/gemm/gemm.scala:21:35
        chek_data_in_valid = _RANDOM[1'h1][0];	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10, src/main/scala/gemm/gemm.scala:22:37
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
      `FIRRTL_AFTER_INITIAL	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign io_c_io_out = accumulation_reg;	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10, src/main/scala/gemm/gemm.scala:21:35
  assign io_data_out_valid = chek_data_in_valid;	// <stdin>:3:10, :38:10, :73:10, :108:10, :143:10, :178:10, :213:10, :248:10, :283:10, :318:10, :353:10, :388:10, :423:10, :458:10, :493:10, :528:10, :563:10, :598:10, :633:10, :668:10, :703:10, :738:10, :773:10, :808:10, :843:10, :878:10, :913:10, :948:10, :983:10, :1018:10, :1053:10, :1088:10, :1123:10, :1158:10, :1193:10, :1228:10, :1263:10, :1298:10, :1333:10, :1368:10, :1403:10, :1438:10, :1473:10, :1508:10, :1543:10, :1578:10, :1613:10, :1648:10, src/main/scala/gemm/gemm.scala:22:37
endmodule

module Mesh(	// <stdin>:1683:10
  input         clock,	// <stdin>:1684:11
                reset,	// <stdin>:1685:11
  input  [7:0]  io_a_io_in_0_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_0_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_0_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_0_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_1_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_1_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_1_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_1_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_2_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_2_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_2_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_2_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_3_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_3_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_3_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_3_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_4_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_4_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_4_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_4_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_5_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_5_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_5_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_5_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_6_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_6_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_6_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_6_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_7_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_7_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_7_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_a_io_in_7_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_0_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_0_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_0_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_0_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_1_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_1_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_1_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_1_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_2_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_2_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_2_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_2_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_3_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_3_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_3_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_3_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_4_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_4_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_4_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_4_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_5_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_5_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_5_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_b_io_in_5_3,	// src/main/scala/gemm/gemm.scala:57:16
  input         io_in_control_data_in_valid,	// src/main/scala/gemm/gemm.scala:57:16
  output [31:0] io_c_io_out_0_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_0_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_0_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_0_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_0_4,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_0_5,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_1_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_1_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_1_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_1_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_1_4,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_1_5,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_2_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_2_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_2_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_2_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_2_4,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_2_5,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_3_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_3_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_3_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_3_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_3_4,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_3_5,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_4_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_4_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_4_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_4_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_4_4,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_4_5,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_5_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_5_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_5_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_5_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_5_4,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_5_5,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_6_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_6_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_6_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_6_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_6_4,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_6_5,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_7_0,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_7_1,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_7_2,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_7_3,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_7_4,	// src/main/scala/gemm/gemm.scala:57:16
                io_c_io_out_7_5,	// src/main/scala/gemm/gemm.scala:57:16
  output        io_data_out_valid	// src/main/scala/gemm/gemm.scala:57:16
);

  Tile mesh_0_0 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_0_0),
    .io_a_io_in_1                (io_a_io_in_0_1),
    .io_a_io_in_2                (io_a_io_in_0_2),
    .io_a_io_in_3                (io_a_io_in_0_3),
    .io_b_io_in_0                (io_b_io_in_0_0),
    .io_b_io_in_1                (io_b_io_in_0_1),
    .io_b_io_in_2                (io_b_io_in_0_2),
    .io_b_io_in_3                (io_b_io_in_0_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_0_0),
    .io_data_out_valid           (io_data_out_valid)
  );
  Tile mesh_0_1 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_0_0),
    .io_a_io_in_1                (io_a_io_in_0_1),
    .io_a_io_in_2                (io_a_io_in_0_2),
    .io_a_io_in_3                (io_a_io_in_0_3),
    .io_b_io_in_0                (io_b_io_in_1_0),
    .io_b_io_in_1                (io_b_io_in_1_1),
    .io_b_io_in_2                (io_b_io_in_1_2),
    .io_b_io_in_3                (io_b_io_in_1_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_0_1),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_0_2 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_0_0),
    .io_a_io_in_1                (io_a_io_in_0_1),
    .io_a_io_in_2                (io_a_io_in_0_2),
    .io_a_io_in_3                (io_a_io_in_0_3),
    .io_b_io_in_0                (io_b_io_in_2_0),
    .io_b_io_in_1                (io_b_io_in_2_1),
    .io_b_io_in_2                (io_b_io_in_2_2),
    .io_b_io_in_3                (io_b_io_in_2_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_0_2),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_0_3 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_0_0),
    .io_a_io_in_1                (io_a_io_in_0_1),
    .io_a_io_in_2                (io_a_io_in_0_2),
    .io_a_io_in_3                (io_a_io_in_0_3),
    .io_b_io_in_0                (io_b_io_in_3_0),
    .io_b_io_in_1                (io_b_io_in_3_1),
    .io_b_io_in_2                (io_b_io_in_3_2),
    .io_b_io_in_3                (io_b_io_in_3_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_0_3),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_0_4 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_0_0),
    .io_a_io_in_1                (io_a_io_in_0_1),
    .io_a_io_in_2                (io_a_io_in_0_2),
    .io_a_io_in_3                (io_a_io_in_0_3),
    .io_b_io_in_0                (io_b_io_in_4_0),
    .io_b_io_in_1                (io_b_io_in_4_1),
    .io_b_io_in_2                (io_b_io_in_4_2),
    .io_b_io_in_3                (io_b_io_in_4_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_0_4),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_0_5 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_0_0),
    .io_a_io_in_1                (io_a_io_in_0_1),
    .io_a_io_in_2                (io_a_io_in_0_2),
    .io_a_io_in_3                (io_a_io_in_0_3),
    .io_b_io_in_0                (io_b_io_in_5_0),
    .io_b_io_in_1                (io_b_io_in_5_1),
    .io_b_io_in_2                (io_b_io_in_5_2),
    .io_b_io_in_3                (io_b_io_in_5_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_0_5),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_1_0 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_1_0),
    .io_a_io_in_1                (io_a_io_in_1_1),
    .io_a_io_in_2                (io_a_io_in_1_2),
    .io_a_io_in_3                (io_a_io_in_1_3),
    .io_b_io_in_0                (io_b_io_in_0_0),
    .io_b_io_in_1                (io_b_io_in_0_1),
    .io_b_io_in_2                (io_b_io_in_0_2),
    .io_b_io_in_3                (io_b_io_in_0_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_1_0),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_1_1 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_1_0),
    .io_a_io_in_1                (io_a_io_in_1_1),
    .io_a_io_in_2                (io_a_io_in_1_2),
    .io_a_io_in_3                (io_a_io_in_1_3),
    .io_b_io_in_0                (io_b_io_in_1_0),
    .io_b_io_in_1                (io_b_io_in_1_1),
    .io_b_io_in_2                (io_b_io_in_1_2),
    .io_b_io_in_3                (io_b_io_in_1_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_1_1),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_1_2 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_1_0),
    .io_a_io_in_1                (io_a_io_in_1_1),
    .io_a_io_in_2                (io_a_io_in_1_2),
    .io_a_io_in_3                (io_a_io_in_1_3),
    .io_b_io_in_0                (io_b_io_in_2_0),
    .io_b_io_in_1                (io_b_io_in_2_1),
    .io_b_io_in_2                (io_b_io_in_2_2),
    .io_b_io_in_3                (io_b_io_in_2_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_1_2),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_1_3 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_1_0),
    .io_a_io_in_1                (io_a_io_in_1_1),
    .io_a_io_in_2                (io_a_io_in_1_2),
    .io_a_io_in_3                (io_a_io_in_1_3),
    .io_b_io_in_0                (io_b_io_in_3_0),
    .io_b_io_in_1                (io_b_io_in_3_1),
    .io_b_io_in_2                (io_b_io_in_3_2),
    .io_b_io_in_3                (io_b_io_in_3_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_1_3),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_1_4 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_1_0),
    .io_a_io_in_1                (io_a_io_in_1_1),
    .io_a_io_in_2                (io_a_io_in_1_2),
    .io_a_io_in_3                (io_a_io_in_1_3),
    .io_b_io_in_0                (io_b_io_in_4_0),
    .io_b_io_in_1                (io_b_io_in_4_1),
    .io_b_io_in_2                (io_b_io_in_4_2),
    .io_b_io_in_3                (io_b_io_in_4_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_1_4),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_1_5 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_1_0),
    .io_a_io_in_1                (io_a_io_in_1_1),
    .io_a_io_in_2                (io_a_io_in_1_2),
    .io_a_io_in_3                (io_a_io_in_1_3),
    .io_b_io_in_0                (io_b_io_in_5_0),
    .io_b_io_in_1                (io_b_io_in_5_1),
    .io_b_io_in_2                (io_b_io_in_5_2),
    .io_b_io_in_3                (io_b_io_in_5_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_1_5),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_2_0 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_2_0),
    .io_a_io_in_1                (io_a_io_in_2_1),
    .io_a_io_in_2                (io_a_io_in_2_2),
    .io_a_io_in_3                (io_a_io_in_2_3),
    .io_b_io_in_0                (io_b_io_in_0_0),
    .io_b_io_in_1                (io_b_io_in_0_1),
    .io_b_io_in_2                (io_b_io_in_0_2),
    .io_b_io_in_3                (io_b_io_in_0_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_2_0),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_2_1 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_2_0),
    .io_a_io_in_1                (io_a_io_in_2_1),
    .io_a_io_in_2                (io_a_io_in_2_2),
    .io_a_io_in_3                (io_a_io_in_2_3),
    .io_b_io_in_0                (io_b_io_in_1_0),
    .io_b_io_in_1                (io_b_io_in_1_1),
    .io_b_io_in_2                (io_b_io_in_1_2),
    .io_b_io_in_3                (io_b_io_in_1_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_2_1),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_2_2 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_2_0),
    .io_a_io_in_1                (io_a_io_in_2_1),
    .io_a_io_in_2                (io_a_io_in_2_2),
    .io_a_io_in_3                (io_a_io_in_2_3),
    .io_b_io_in_0                (io_b_io_in_2_0),
    .io_b_io_in_1                (io_b_io_in_2_1),
    .io_b_io_in_2                (io_b_io_in_2_2),
    .io_b_io_in_3                (io_b_io_in_2_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_2_2),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_2_3 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_2_0),
    .io_a_io_in_1                (io_a_io_in_2_1),
    .io_a_io_in_2                (io_a_io_in_2_2),
    .io_a_io_in_3                (io_a_io_in_2_3),
    .io_b_io_in_0                (io_b_io_in_3_0),
    .io_b_io_in_1                (io_b_io_in_3_1),
    .io_b_io_in_2                (io_b_io_in_3_2),
    .io_b_io_in_3                (io_b_io_in_3_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_2_3),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_2_4 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_2_0),
    .io_a_io_in_1                (io_a_io_in_2_1),
    .io_a_io_in_2                (io_a_io_in_2_2),
    .io_a_io_in_3                (io_a_io_in_2_3),
    .io_b_io_in_0                (io_b_io_in_4_0),
    .io_b_io_in_1                (io_b_io_in_4_1),
    .io_b_io_in_2                (io_b_io_in_4_2),
    .io_b_io_in_3                (io_b_io_in_4_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_2_4),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_2_5 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_2_0),
    .io_a_io_in_1                (io_a_io_in_2_1),
    .io_a_io_in_2                (io_a_io_in_2_2),
    .io_a_io_in_3                (io_a_io_in_2_3),
    .io_b_io_in_0                (io_b_io_in_5_0),
    .io_b_io_in_1                (io_b_io_in_5_1),
    .io_b_io_in_2                (io_b_io_in_5_2),
    .io_b_io_in_3                (io_b_io_in_5_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_2_5),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_3_0 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_3_0),
    .io_a_io_in_1                (io_a_io_in_3_1),
    .io_a_io_in_2                (io_a_io_in_3_2),
    .io_a_io_in_3                (io_a_io_in_3_3),
    .io_b_io_in_0                (io_b_io_in_0_0),
    .io_b_io_in_1                (io_b_io_in_0_1),
    .io_b_io_in_2                (io_b_io_in_0_2),
    .io_b_io_in_3                (io_b_io_in_0_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_3_0),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_3_1 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_3_0),
    .io_a_io_in_1                (io_a_io_in_3_1),
    .io_a_io_in_2                (io_a_io_in_3_2),
    .io_a_io_in_3                (io_a_io_in_3_3),
    .io_b_io_in_0                (io_b_io_in_1_0),
    .io_b_io_in_1                (io_b_io_in_1_1),
    .io_b_io_in_2                (io_b_io_in_1_2),
    .io_b_io_in_3                (io_b_io_in_1_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_3_1),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_3_2 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_3_0),
    .io_a_io_in_1                (io_a_io_in_3_1),
    .io_a_io_in_2                (io_a_io_in_3_2),
    .io_a_io_in_3                (io_a_io_in_3_3),
    .io_b_io_in_0                (io_b_io_in_2_0),
    .io_b_io_in_1                (io_b_io_in_2_1),
    .io_b_io_in_2                (io_b_io_in_2_2),
    .io_b_io_in_3                (io_b_io_in_2_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_3_2),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_3_3 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_3_0),
    .io_a_io_in_1                (io_a_io_in_3_1),
    .io_a_io_in_2                (io_a_io_in_3_2),
    .io_a_io_in_3                (io_a_io_in_3_3),
    .io_b_io_in_0                (io_b_io_in_3_0),
    .io_b_io_in_1                (io_b_io_in_3_1),
    .io_b_io_in_2                (io_b_io_in_3_2),
    .io_b_io_in_3                (io_b_io_in_3_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_3_3),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_3_4 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_3_0),
    .io_a_io_in_1                (io_a_io_in_3_1),
    .io_a_io_in_2                (io_a_io_in_3_2),
    .io_a_io_in_3                (io_a_io_in_3_3),
    .io_b_io_in_0                (io_b_io_in_4_0),
    .io_b_io_in_1                (io_b_io_in_4_1),
    .io_b_io_in_2                (io_b_io_in_4_2),
    .io_b_io_in_3                (io_b_io_in_4_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_3_4),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_3_5 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_3_0),
    .io_a_io_in_1                (io_a_io_in_3_1),
    .io_a_io_in_2                (io_a_io_in_3_2),
    .io_a_io_in_3                (io_a_io_in_3_3),
    .io_b_io_in_0                (io_b_io_in_5_0),
    .io_b_io_in_1                (io_b_io_in_5_1),
    .io_b_io_in_2                (io_b_io_in_5_2),
    .io_b_io_in_3                (io_b_io_in_5_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_3_5),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_4_0 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_4_0),
    .io_a_io_in_1                (io_a_io_in_4_1),
    .io_a_io_in_2                (io_a_io_in_4_2),
    .io_a_io_in_3                (io_a_io_in_4_3),
    .io_b_io_in_0                (io_b_io_in_0_0),
    .io_b_io_in_1                (io_b_io_in_0_1),
    .io_b_io_in_2                (io_b_io_in_0_2),
    .io_b_io_in_3                (io_b_io_in_0_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_4_0),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_4_1 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_4_0),
    .io_a_io_in_1                (io_a_io_in_4_1),
    .io_a_io_in_2                (io_a_io_in_4_2),
    .io_a_io_in_3                (io_a_io_in_4_3),
    .io_b_io_in_0                (io_b_io_in_1_0),
    .io_b_io_in_1                (io_b_io_in_1_1),
    .io_b_io_in_2                (io_b_io_in_1_2),
    .io_b_io_in_3                (io_b_io_in_1_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_4_1),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_4_2 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_4_0),
    .io_a_io_in_1                (io_a_io_in_4_1),
    .io_a_io_in_2                (io_a_io_in_4_2),
    .io_a_io_in_3                (io_a_io_in_4_3),
    .io_b_io_in_0                (io_b_io_in_2_0),
    .io_b_io_in_1                (io_b_io_in_2_1),
    .io_b_io_in_2                (io_b_io_in_2_2),
    .io_b_io_in_3                (io_b_io_in_2_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_4_2),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_4_3 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_4_0),
    .io_a_io_in_1                (io_a_io_in_4_1),
    .io_a_io_in_2                (io_a_io_in_4_2),
    .io_a_io_in_3                (io_a_io_in_4_3),
    .io_b_io_in_0                (io_b_io_in_3_0),
    .io_b_io_in_1                (io_b_io_in_3_1),
    .io_b_io_in_2                (io_b_io_in_3_2),
    .io_b_io_in_3                (io_b_io_in_3_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_4_3),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_4_4 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_4_0),
    .io_a_io_in_1                (io_a_io_in_4_1),
    .io_a_io_in_2                (io_a_io_in_4_2),
    .io_a_io_in_3                (io_a_io_in_4_3),
    .io_b_io_in_0                (io_b_io_in_4_0),
    .io_b_io_in_1                (io_b_io_in_4_1),
    .io_b_io_in_2                (io_b_io_in_4_2),
    .io_b_io_in_3                (io_b_io_in_4_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_4_4),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_4_5 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_4_0),
    .io_a_io_in_1                (io_a_io_in_4_1),
    .io_a_io_in_2                (io_a_io_in_4_2),
    .io_a_io_in_3                (io_a_io_in_4_3),
    .io_b_io_in_0                (io_b_io_in_5_0),
    .io_b_io_in_1                (io_b_io_in_5_1),
    .io_b_io_in_2                (io_b_io_in_5_2),
    .io_b_io_in_3                (io_b_io_in_5_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_4_5),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_5_0 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_5_0),
    .io_a_io_in_1                (io_a_io_in_5_1),
    .io_a_io_in_2                (io_a_io_in_5_2),
    .io_a_io_in_3                (io_a_io_in_5_3),
    .io_b_io_in_0                (io_b_io_in_0_0),
    .io_b_io_in_1                (io_b_io_in_0_1),
    .io_b_io_in_2                (io_b_io_in_0_2),
    .io_b_io_in_3                (io_b_io_in_0_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_5_0),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_5_1 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_5_0),
    .io_a_io_in_1                (io_a_io_in_5_1),
    .io_a_io_in_2                (io_a_io_in_5_2),
    .io_a_io_in_3                (io_a_io_in_5_3),
    .io_b_io_in_0                (io_b_io_in_1_0),
    .io_b_io_in_1                (io_b_io_in_1_1),
    .io_b_io_in_2                (io_b_io_in_1_2),
    .io_b_io_in_3                (io_b_io_in_1_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_5_1),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_5_2 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_5_0),
    .io_a_io_in_1                (io_a_io_in_5_1),
    .io_a_io_in_2                (io_a_io_in_5_2),
    .io_a_io_in_3                (io_a_io_in_5_3),
    .io_b_io_in_0                (io_b_io_in_2_0),
    .io_b_io_in_1                (io_b_io_in_2_1),
    .io_b_io_in_2                (io_b_io_in_2_2),
    .io_b_io_in_3                (io_b_io_in_2_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_5_2),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_5_3 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_5_0),
    .io_a_io_in_1                (io_a_io_in_5_1),
    .io_a_io_in_2                (io_a_io_in_5_2),
    .io_a_io_in_3                (io_a_io_in_5_3),
    .io_b_io_in_0                (io_b_io_in_3_0),
    .io_b_io_in_1                (io_b_io_in_3_1),
    .io_b_io_in_2                (io_b_io_in_3_2),
    .io_b_io_in_3                (io_b_io_in_3_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_5_3),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_5_4 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_5_0),
    .io_a_io_in_1                (io_a_io_in_5_1),
    .io_a_io_in_2                (io_a_io_in_5_2),
    .io_a_io_in_3                (io_a_io_in_5_3),
    .io_b_io_in_0                (io_b_io_in_4_0),
    .io_b_io_in_1                (io_b_io_in_4_1),
    .io_b_io_in_2                (io_b_io_in_4_2),
    .io_b_io_in_3                (io_b_io_in_4_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_5_4),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_5_5 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_5_0),
    .io_a_io_in_1                (io_a_io_in_5_1),
    .io_a_io_in_2                (io_a_io_in_5_2),
    .io_a_io_in_3                (io_a_io_in_5_3),
    .io_b_io_in_0                (io_b_io_in_5_0),
    .io_b_io_in_1                (io_b_io_in_5_1),
    .io_b_io_in_2                (io_b_io_in_5_2),
    .io_b_io_in_3                (io_b_io_in_5_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_5_5),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_6_0 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_6_0),
    .io_a_io_in_1                (io_a_io_in_6_1),
    .io_a_io_in_2                (io_a_io_in_6_2),
    .io_a_io_in_3                (io_a_io_in_6_3),
    .io_b_io_in_0                (io_b_io_in_0_0),
    .io_b_io_in_1                (io_b_io_in_0_1),
    .io_b_io_in_2                (io_b_io_in_0_2),
    .io_b_io_in_3                (io_b_io_in_0_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_6_0),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_6_1 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_6_0),
    .io_a_io_in_1                (io_a_io_in_6_1),
    .io_a_io_in_2                (io_a_io_in_6_2),
    .io_a_io_in_3                (io_a_io_in_6_3),
    .io_b_io_in_0                (io_b_io_in_1_0),
    .io_b_io_in_1                (io_b_io_in_1_1),
    .io_b_io_in_2                (io_b_io_in_1_2),
    .io_b_io_in_3                (io_b_io_in_1_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_6_1),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_6_2 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_6_0),
    .io_a_io_in_1                (io_a_io_in_6_1),
    .io_a_io_in_2                (io_a_io_in_6_2),
    .io_a_io_in_3                (io_a_io_in_6_3),
    .io_b_io_in_0                (io_b_io_in_2_0),
    .io_b_io_in_1                (io_b_io_in_2_1),
    .io_b_io_in_2                (io_b_io_in_2_2),
    .io_b_io_in_3                (io_b_io_in_2_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_6_2),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_6_3 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_6_0),
    .io_a_io_in_1                (io_a_io_in_6_1),
    .io_a_io_in_2                (io_a_io_in_6_2),
    .io_a_io_in_3                (io_a_io_in_6_3),
    .io_b_io_in_0                (io_b_io_in_3_0),
    .io_b_io_in_1                (io_b_io_in_3_1),
    .io_b_io_in_2                (io_b_io_in_3_2),
    .io_b_io_in_3                (io_b_io_in_3_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_6_3),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_6_4 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_6_0),
    .io_a_io_in_1                (io_a_io_in_6_1),
    .io_a_io_in_2                (io_a_io_in_6_2),
    .io_a_io_in_3                (io_a_io_in_6_3),
    .io_b_io_in_0                (io_b_io_in_4_0),
    .io_b_io_in_1                (io_b_io_in_4_1),
    .io_b_io_in_2                (io_b_io_in_4_2),
    .io_b_io_in_3                (io_b_io_in_4_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_6_4),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_6_5 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_6_0),
    .io_a_io_in_1                (io_a_io_in_6_1),
    .io_a_io_in_2                (io_a_io_in_6_2),
    .io_a_io_in_3                (io_a_io_in_6_3),
    .io_b_io_in_0                (io_b_io_in_5_0),
    .io_b_io_in_1                (io_b_io_in_5_1),
    .io_b_io_in_2                (io_b_io_in_5_2),
    .io_b_io_in_3                (io_b_io_in_5_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_6_5),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_7_0 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_7_0),
    .io_a_io_in_1                (io_a_io_in_7_1),
    .io_a_io_in_2                (io_a_io_in_7_2),
    .io_a_io_in_3                (io_a_io_in_7_3),
    .io_b_io_in_0                (io_b_io_in_0_0),
    .io_b_io_in_1                (io_b_io_in_0_1),
    .io_b_io_in_2                (io_b_io_in_0_2),
    .io_b_io_in_3                (io_b_io_in_0_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_7_0),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_7_1 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_7_0),
    .io_a_io_in_1                (io_a_io_in_7_1),
    .io_a_io_in_2                (io_a_io_in_7_2),
    .io_a_io_in_3                (io_a_io_in_7_3),
    .io_b_io_in_0                (io_b_io_in_1_0),
    .io_b_io_in_1                (io_b_io_in_1_1),
    .io_b_io_in_2                (io_b_io_in_1_2),
    .io_b_io_in_3                (io_b_io_in_1_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_7_1),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_7_2 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_7_0),
    .io_a_io_in_1                (io_a_io_in_7_1),
    .io_a_io_in_2                (io_a_io_in_7_2),
    .io_a_io_in_3                (io_a_io_in_7_3),
    .io_b_io_in_0                (io_b_io_in_2_0),
    .io_b_io_in_1                (io_b_io_in_2_1),
    .io_b_io_in_2                (io_b_io_in_2_2),
    .io_b_io_in_3                (io_b_io_in_2_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_7_2),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_7_3 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_7_0),
    .io_a_io_in_1                (io_a_io_in_7_1),
    .io_a_io_in_2                (io_a_io_in_7_2),
    .io_a_io_in_3                (io_a_io_in_7_3),
    .io_b_io_in_0                (io_b_io_in_3_0),
    .io_b_io_in_1                (io_b_io_in_3_1),
    .io_b_io_in_2                (io_b_io_in_3_2),
    .io_b_io_in_3                (io_b_io_in_3_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_7_3),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_7_4 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_7_0),
    .io_a_io_in_1                (io_a_io_in_7_1),
    .io_a_io_in_2                (io_a_io_in_7_2),
    .io_a_io_in_3                (io_a_io_in_7_3),
    .io_b_io_in_0                (io_b_io_in_4_0),
    .io_b_io_in_1                (io_b_io_in_4_1),
    .io_b_io_in_2                (io_b_io_in_4_2),
    .io_b_io_in_3                (io_b_io_in_4_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_7_4),
    .io_data_out_valid           (/* unused */)
  );
  Tile mesh_7_5 (	// src/main/scala/gemm/gemm.scala:61:74
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0                (io_a_io_in_7_0),
    .io_a_io_in_1                (io_a_io_in_7_1),
    .io_a_io_in_2                (io_a_io_in_7_2),
    .io_a_io_in_3                (io_a_io_in_7_3),
    .io_b_io_in_0                (io_b_io_in_5_0),
    .io_b_io_in_1                (io_b_io_in_5_1),
    .io_b_io_in_2                (io_b_io_in_5_2),
    .io_b_io_in_3                (io_b_io_in_5_3),
    .io_in_control_data_in_valid (io_in_control_data_in_valid),
    .io_c_io_out                 (io_c_io_out_7_5),
    .io_data_out_valid           (/* unused */)
  );
endmodule

module Gemm(	// <stdin>:2026:10
  input           clock,	// <stdin>:2027:11
                  reset,	// <stdin>:2028:11
                  io_data_in_valid,	// src/main/scala/gemm/gemm.scala:84:16
  input  [255:0]  io_a_io_in,	// src/main/scala/gemm/gemm.scala:84:16
  input  [191:0]  io_b_io_in,	// src/main/scala/gemm/gemm.scala:84:16
  output          io_data_out_valid,	// src/main/scala/gemm/gemm.scala:84:16
  output [1535:0] io_c_io_out	// src/main/scala/gemm/gemm.scala:84:16
);

  wire [31:0] _mesh_io_c_io_out_0_0;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_0_1;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_0_2;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_0_3;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_0_4;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_0_5;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_1_0;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_1_1;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_1_2;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_1_3;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_1_4;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_1_5;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_2_0;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_2_1;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_2_2;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_2_3;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_2_4;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_2_5;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_3_0;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_3_1;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_3_2;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_3_3;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_3_4;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_3_5;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_4_0;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_4_1;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_4_2;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_4_3;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_4_4;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_4_5;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_5_0;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_5_1;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_5_2;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_5_3;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_5_4;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_5_5;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_6_0;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_6_1;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_6_2;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_6_3;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_6_4;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_6_5;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_7_0;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_7_1;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_7_2;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_7_3;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_7_4;	// src/main/scala/gemm/gemm.scala:86:22
  wire [31:0] _mesh_io_c_io_out_7_5;	// src/main/scala/gemm/gemm.scala:86:22
  Mesh mesh (	// src/main/scala/gemm/gemm.scala:86:22
    .clock                       (clock),
    .reset                       (reset),
    .io_a_io_in_0_0              (io_a_io_in[7:0]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_0_1              (io_a_io_in[15:8]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_0_2              (io_a_io_in[23:16]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_0_3              (io_a_io_in[31:24]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_1_0              (io_a_io_in[39:32]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_1_1              (io_a_io_in[47:40]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_1_2              (io_a_io_in[55:48]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_1_3              (io_a_io_in[63:56]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_2_0              (io_a_io_in[71:64]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_2_1              (io_a_io_in[79:72]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_2_2              (io_a_io_in[87:80]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_2_3              (io_a_io_in[95:88]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_3_0              (io_a_io_in[103:96]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_3_1              (io_a_io_in[111:104]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_3_2              (io_a_io_in[119:112]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_3_3              (io_a_io_in[127:120]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_4_0              (io_a_io_in[135:128]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_4_1              (io_a_io_in[143:136]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_4_2              (io_a_io_in[151:144]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_4_3              (io_a_io_in[159:152]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_5_0              (io_a_io_in[167:160]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_5_1              (io_a_io_in[175:168]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_5_2              (io_a_io_in[183:176]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_5_3              (io_a_io_in[191:184]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_6_0              (io_a_io_in[199:192]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_6_1              (io_a_io_in[207:200]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_6_2              (io_a_io_in[215:208]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_6_3              (io_a_io_in[223:216]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_7_0              (io_a_io_in[231:224]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_7_1              (io_a_io_in[239:232]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_7_2              (io_a_io_in[247:240]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_a_io_in_7_3              (io_a_io_in[255:248]),	// src/main/scala/gemm/gemm.scala:96:42
    .io_b_io_in_0_0              (io_b_io_in[7:0]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_0_1              (io_b_io_in[15:8]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_0_2              (io_b_io_in[23:16]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_0_3              (io_b_io_in[31:24]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_1_0              (io_b_io_in[39:32]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_1_1              (io_b_io_in[47:40]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_1_2              (io_b_io_in[55:48]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_1_3              (io_b_io_in[63:56]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_2_0              (io_b_io_in[71:64]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_2_1              (io_b_io_in[79:72]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_2_2              (io_b_io_in[87:80]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_2_3              (io_b_io_in[95:88]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_3_0              (io_b_io_in[103:96]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_3_1              (io_b_io_in[111:104]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_3_2              (io_b_io_in[119:112]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_3_3              (io_b_io_in[127:120]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_4_0              (io_b_io_in[135:128]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_4_1              (io_b_io_in[143:136]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_4_2              (io_b_io_in[151:144]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_4_3              (io_b_io_in[159:152]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_5_0              (io_b_io_in[167:160]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_5_1              (io_b_io_in[175:168]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_5_2              (io_b_io_in[183:176]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_b_io_in_5_3              (io_b_io_in[191:184]),	// src/main/scala/gemm/gemm.scala:102:42
    .io_in_control_data_in_valid (io_data_in_valid),
    .io_c_io_out_0_0             (_mesh_io_c_io_out_0_0),
    .io_c_io_out_0_1             (_mesh_io_c_io_out_0_1),
    .io_c_io_out_0_2             (_mesh_io_c_io_out_0_2),
    .io_c_io_out_0_3             (_mesh_io_c_io_out_0_3),
    .io_c_io_out_0_4             (_mesh_io_c_io_out_0_4),
    .io_c_io_out_0_5             (_mesh_io_c_io_out_0_5),
    .io_c_io_out_1_0             (_mesh_io_c_io_out_1_0),
    .io_c_io_out_1_1             (_mesh_io_c_io_out_1_1),
    .io_c_io_out_1_2             (_mesh_io_c_io_out_1_2),
    .io_c_io_out_1_3             (_mesh_io_c_io_out_1_3),
    .io_c_io_out_1_4             (_mesh_io_c_io_out_1_4),
    .io_c_io_out_1_5             (_mesh_io_c_io_out_1_5),
    .io_c_io_out_2_0             (_mesh_io_c_io_out_2_0),
    .io_c_io_out_2_1             (_mesh_io_c_io_out_2_1),
    .io_c_io_out_2_2             (_mesh_io_c_io_out_2_2),
    .io_c_io_out_2_3             (_mesh_io_c_io_out_2_3),
    .io_c_io_out_2_4             (_mesh_io_c_io_out_2_4),
    .io_c_io_out_2_5             (_mesh_io_c_io_out_2_5),
    .io_c_io_out_3_0             (_mesh_io_c_io_out_3_0),
    .io_c_io_out_3_1             (_mesh_io_c_io_out_3_1),
    .io_c_io_out_3_2             (_mesh_io_c_io_out_3_2),
    .io_c_io_out_3_3             (_mesh_io_c_io_out_3_3),
    .io_c_io_out_3_4             (_mesh_io_c_io_out_3_4),
    .io_c_io_out_3_5             (_mesh_io_c_io_out_3_5),
    .io_c_io_out_4_0             (_mesh_io_c_io_out_4_0),
    .io_c_io_out_4_1             (_mesh_io_c_io_out_4_1),
    .io_c_io_out_4_2             (_mesh_io_c_io_out_4_2),
    .io_c_io_out_4_3             (_mesh_io_c_io_out_4_3),
    .io_c_io_out_4_4             (_mesh_io_c_io_out_4_4),
    .io_c_io_out_4_5             (_mesh_io_c_io_out_4_5),
    .io_c_io_out_5_0             (_mesh_io_c_io_out_5_0),
    .io_c_io_out_5_1             (_mesh_io_c_io_out_5_1),
    .io_c_io_out_5_2             (_mesh_io_c_io_out_5_2),
    .io_c_io_out_5_3             (_mesh_io_c_io_out_5_3),
    .io_c_io_out_5_4             (_mesh_io_c_io_out_5_4),
    .io_c_io_out_5_5             (_mesh_io_c_io_out_5_5),
    .io_c_io_out_6_0             (_mesh_io_c_io_out_6_0),
    .io_c_io_out_6_1             (_mesh_io_c_io_out_6_1),
    .io_c_io_out_6_2             (_mesh_io_c_io_out_6_2),
    .io_c_io_out_6_3             (_mesh_io_c_io_out_6_3),
    .io_c_io_out_6_4             (_mesh_io_c_io_out_6_4),
    .io_c_io_out_6_5             (_mesh_io_c_io_out_6_5),
    .io_c_io_out_7_0             (_mesh_io_c_io_out_7_0),
    .io_c_io_out_7_1             (_mesh_io_c_io_out_7_1),
    .io_c_io_out_7_2             (_mesh_io_c_io_out_7_2),
    .io_c_io_out_7_3             (_mesh_io_c_io_out_7_3),
    .io_c_io_out_7_4             (_mesh_io_c_io_out_7_4),
    .io_c_io_out_7_5             (_mesh_io_c_io_out_7_5),
    .io_data_out_valid           (io_data_out_valid)
  );
  assign io_c_io_out =
    {144'h0,
     _mesh_io_c_io_out_7_5[7:0],
     _mesh_io_c_io_out_7_4[7:0],
     _mesh_io_c_io_out_7_3[7:0],
     _mesh_io_c_io_out_7_2[7:0],
     _mesh_io_c_io_out_7_1[7:0],
     _mesh_io_c_io_out_7_0[7:0],
     144'h0,
     _mesh_io_c_io_out_6_5[7:0],
     _mesh_io_c_io_out_6_4[7:0],
     _mesh_io_c_io_out_6_3[7:0],
     _mesh_io_c_io_out_6_2[7:0],
     _mesh_io_c_io_out_6_1[7:0],
     _mesh_io_c_io_out_6_0[7:0],
     144'h0,
     _mesh_io_c_io_out_5_5[7:0],
     _mesh_io_c_io_out_5_4[7:0],
     _mesh_io_c_io_out_5_3[7:0],
     _mesh_io_c_io_out_5_2[7:0],
     _mesh_io_c_io_out_5_1[7:0],
     _mesh_io_c_io_out_5_0[7:0],
     144'h0,
     _mesh_io_c_io_out_4_5[7:0],
     _mesh_io_c_io_out_4_4[7:0],
     _mesh_io_c_io_out_4_3[7:0],
     _mesh_io_c_io_out_4_2[7:0],
     _mesh_io_c_io_out_4_1[7:0],
     _mesh_io_c_io_out_4_0[7:0],
     144'h0,
     _mesh_io_c_io_out_3_5[7:0],
     _mesh_io_c_io_out_3_4[7:0],
     _mesh_io_c_io_out_3_3[7:0],
     _mesh_io_c_io_out_3_2[7:0],
     _mesh_io_c_io_out_3_1[7:0],
     _mesh_io_c_io_out_3_0[7:0],
     144'h0,
     _mesh_io_c_io_out_2_5[7:0],
     _mesh_io_c_io_out_2_4[7:0],
     _mesh_io_c_io_out_2_3[7:0],
     _mesh_io_c_io_out_2_2[7:0],
     _mesh_io_c_io_out_2_1[7:0],
     _mesh_io_c_io_out_2_0[7:0],
     144'h0,
     _mesh_io_c_io_out_1_5[7:0],
     _mesh_io_c_io_out_1_4[7:0],
     _mesh_io_c_io_out_1_3[7:0],
     _mesh_io_c_io_out_1_2[7:0],
     _mesh_io_c_io_out_1_1[7:0],
     _mesh_io_c_io_out_1_0[7:0],
     144'h0,
     _mesh_io_c_io_out_0_5[7:0],
     _mesh_io_c_io_out_0_4[7:0],
     _mesh_io_c_io_out_0_3[7:0],
     _mesh_io_c_io_out_0_2[7:0],
     _mesh_io_c_io_out_0_1[7:0],
     _mesh_io_c_io_out_0_0[7:0]};	// <stdin>:2026:10, src/main/scala/gemm/gemm.scala:86:22, :108:30, :110:25, :116:23
endmodule

