name: Check format
on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs: 
  run:
    name: Build and Run
    strategy:
      matrix:
        java-version: [17]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: sbt

      - name: check format
        run: sbt scalafmtCheck