name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  
jobs: 
  run:
    name: Build and Run
    strategy:
      matrix:
        java-version: [8, 11, 17]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: sbt

      - name: Run the project
        run: sbt run

      - name: Run the unit tests
        run: sbt test
